/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school21_smartcalc_model_Model */

#ifndef _Included_edu_school21_smartcalc_model_Model
#define _Included_edu_school21_smartcalc_model_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school21_smartcalc_model_Model
 * Method:    performCalculation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_school21_smartcalc_model_Model_performCalculation
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

